from __future__ import annotations

from io import BytesIO

from app.app.files.domain import mediatypes


class TestGuess:
    def test_on_jpeg_image(self) -> None:
        jpeg_header = BytesIO(b'\xff\xd8\xff\xe0\x00\x10')
        assert mediatypes.guess(jpeg_header) == "image/jpeg"

    def test_on_svg_image(self) -> None:
        svg_header = BytesIO(
            b'<svg width="300" height="130" xmlns="http://www.w3.org/2000/svg" />'
        )
        assert mediatypes.guess(svg_header) == "image/svg+xml"

    def test_on_svg_with_comment_before_root(self) -> None:
        content = BytesIO(
            b'<!-- generated by tool --><svg xmlns="http://www.w3.org/2000/svg"/>'
        )
        assert mediatypes.guess(content) == "image/svg+xml"

    def test_on_svg_with_xml_declaration_and_comment(self) -> None:
        content = BytesIO(
            b'<?xml version="1.0"?>\n'
            b'<!-- header comment -->\n'
            b'<svg xmlns="http://www.w3.org/2000/svg"/>'
        )
        assert mediatypes.guess(content) == "image/svg+xml"

    def test_on_svg_with_multiple_comments(self) -> None:
        content = BytesIO(
            b'<!-- first -->\n'
            b'<!-- second -->\n'
            b'<svg xmlns="http://www.w3.org/2000/svg"/>'
        )
        assert mediatypes.guess(content) == "image/svg+xml"

    def test_on_svg_with_xml_declaration(self) -> None:
        content = BytesIO(
            b'<?xml version="1.0" encoding="UTF-8"?>\n'
            b'<svg xmlns="http://www.w3.org/2000/svg"/>'
        )
        assert mediatypes.guess(content) == "image/svg+xml"

    def test_on_svg_with_doctype(self) -> None:
        content = BytesIO(
            b'<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">'
            b'<svg xmlns="http://www.w3.org/2000/svg"/>'
        )
        assert mediatypes.guess(content) == "image/svg+xml"

    def test_on_svg_with_xml_declaration_and_doctype(self) -> None:
        content = BytesIO(
            b'<?xml version="1.0"?>\n'
            b'<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">'
            b'<svg xmlns="http://www.w3.org/2000/svg"/>'
        )
        assert mediatypes.guess(content) == "image/svg+xml"

    def test_on_unknown_content(self) -> None:
        content = BytesIO(b"Dummy")
        assert mediatypes.guess(content) == mediatypes.OCTET_STREAM

    def test_fallback_to_filename_for_unknown_content(self):
        content = BytesIO(b"dummy")
        assert mediatypes.guess(content, name="f.txt") == "text/plain"

    def test_no_fallback_to_filename_for_strict_extension(self):
        content = BytesIO(b"dummy")
        assert mediatypes.guess(content, name="im.jpeg") == mediatypes.OCTET_STREAM


class TestGuessUnsafe:
    def test_on_jpeg_image(self) -> None:
        assert mediatypes.guess_unsafe("img.jpeg") == "image/jpeg"

    def test_when_no_extenstion(self) -> None:
        assert mediatypes.guess_unsafe("f") == mediatypes.OCTET_STREAM
