version: 2

updates:
- package-ecosystem: "uv"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    patch:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "patch"
    minor-and-patch:
      applies-to: security-updates
      patterns:
        - "*"
      update-types:
        - "patch"
        - "minor"

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    actions-all:
      patterns:
        - "*"
