default_language_version:
    python: python3
repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.286'
    hooks:
    -   id: ruff
        args: ["--fix"]
-   repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python3 -m mypy
        args: ["--new-type-inference"]
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
