services:
  # edgedb:
  #   image: edgedb/edgedb:1-beta2
  #   environment:
  #     - EDGEDB_USER=edgedb
  #     - EDGEDB_PASSWORD=root
  #   volumes:
  #     - dbvolume:/var/lib/edgedb/data
  #   ports:
  #     - "5656:5656"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  dbvolume: {}
