services:
  edgedb:
    image: edgedb/edgedb:1
    environment:
      - EDGEDB_USER=edgedb
      - EDGEDB_PASSWORD=root
      - EDGEDB_TLS_CERT_FILE=/certs/edbtlscert.dev.pem
      - EDGEDB_TLS_KEY_FILE=/certs/edbprivkey.dev.pem
    volumes:
      - dbvolume:/var/lib/edgedb/data
      - ./certs:/certs
    ports:
      - "5656:5656"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  minio:
    image: fdooch/minio:RELEASE.2022-05-26T05-48-41Z
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    volumes:
      - shelf-minio-volume:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

volumes:
  dbvolume: {}
  shelf-minio-volume: {}
