services:
  edgedb:
    image: edgedb/edgedb:3.3
    environment:
      - EDGEDB_SERVER_USER=edgedb
      - EDGEDB_SERVER_PASSWORD=root
      - EDGEDB_SERVER_TLS_KEY_FILE=/certs/edbprivkey.dev.pem
      - EDGEDB_SERVER_TLS_CERT_FILE=/certs/edbtlscert.dev.pem
    volumes:
      - dbvolume:/var/lib/edgedb/data
      - ./certs:/certs
    ports:
      - "5656:5656"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
      - MINIO_VOLUMES="/mnt/data"
    volumes:
      - shelf-minio-volume:/mnt/data
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"

volumes:
  dbvolume: {}
  shelf-minio-volume: {}
