services:
  edgedb:
    image: edgedb/edgedb:1-alpha7
    environment:
      - EDGEDB_USER=edgedb
      - EDGEDB_PASSWORD=root
    volumes:
      - dbvolume:/var/lib/edgedb/data
    ports:
      - "5656:5656"

volumes:
  dbvolume: {}
