services:
  gel:
    image: geldata/gel:6.9
    environment:
      - GEL_SERVER_USER=gel
      - GEL_SERVER_PASSWORD=root
      - GEL_SERVER_TLS_KEY_FILE=/certs/edbprivkey.dev.pem
      - GEL_SERVER_TLS_CERT_FILE=/certs/edbtlscert.dev.pem
    volumes:
      - dbvolume:/var/lib/gel/data
      - ./certs:/certs
    ports:
      - "5656:5656"

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web interface port

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z@sha256:f6efb212cad3b62f78ca02339f16d8bc28d5bb2fbe792dfc21225c6037d2af8b
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    volumes:
      - shelf-minio-volume-test-1:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


volumes:
  dbvolume: {}
  shelf-minio-volume: {}
  shelf-minio-volume-test-1: {}
