from __future__ import annotations

import uuid

import pytest

from app.app.photos.domain import Album


class TestAutogenerateSlug:
    def test_slug_autogenerated(self):
        # WHEN
        album = Album(
            id=uuid.uuid4(),
            owner_id=uuid.uuid4(),
            title="My Album Title",
        )
        # THEN
        assert album.slug == "my-album-title"

    def test_no_slug_generation_when_slug_explicitly_provided(self):
        # WHEN
        album = Album(
            id=uuid.uuid4(),
            owner_id=uuid.uuid4(),
            title="My Album Title",
            slug="custom-slug",
        )
        # THEN
        assert album.slug == "custom-slug"

    def test_no_slug_generation_when_slug_is_empty_string(self):
        # WHEN
        album = Album(
            id=uuid.uuid4(),
            owner_id=uuid.uuid4(),
            title="My Album Title",
            slug="",
        )
        # THEN
        assert album.slug == "my-album-title"

    def test_no_slug_generation_when_title_is_not_provided(self):
        with pytest.raises(ValueError):
            Album(  # type: ignore[call-arg]
                id=uuid.uuid4(),
                owner_id=uuid.uuid4(),
                slug="",
            )
