name: Lint

on:
    push:
      branches:
        - master
      tags:
        - '[0-2].[0-9]+.[0-9]+*'
    pull_request:
      branches:
        - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.12
      uses: actions/setup-python@master
      with:
        python-version: "3.12"

    - name: Cache pip dependencies
      uses: actions/cache@master
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('requirements/lint.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache pre-commit dependencies
      uses: actions/cache@master
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/lint.txt

    - name: Run Linters
      run: |
        pre-commit run --all-files
